import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar"
import Providers from "@/components/Providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body className="bg-earth-50 text-earth-900 antialiased h-screen overflow-hidden">
    <Providers>
    <div className="flex flex-col h-full bg-earth-50 font-sans">
        <Navbar />
        <main className="flex-1 overflow-hidden relative">
            {children}
        </main>
    </div>
    </Providers>
    </body>
    </html>
  );
}
