export interface Item {
    id: string;
    name: string;
    description: string;
    pricePerDay: number;
    replacementCost: number;
    category: 'unterkunft' | 'kochen' | 'schlafen' | 'beleuchtung' | 'sonstiges';
    imageUrl: string;
    totalStock: number;
    availableStock: number;
}

export interface CartItem extends Item {
    quantity: number;
}

export enum BookingStatus {
    PENDING = 'PENDING',
    APPROVED = 'APPROVED',
    ACTIVE = 'ACTIVE', // Picked up
    COMPLETED = 'COMPLETED', // Returned and paid
    CANCELLED = 'CANCELLED'
}

export interface BrokenItemRecord {
    itemId: string;
    name: string;
    count: number;
    cost: number;
}

export interface Booking {
    id: string;
    userName: string;
    items: CartItem[];
    startDate: string; // ISO Date string
    endDate: string; // ISO Date string
    status: BookingStatus;
    totalRentalCost: number;
    brokenItems?: BrokenItemRecord[];
    finalBillAmount?: number;
    adminNotes?: string; // Generated by AI usually
    createdAt: number;
}

export type ViewState = 'LANDING' | 'USER_BROWSE' | 'ADMIN_DASHBOARD';